# Generated by Django 6.0.6 on 2026-06-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('icone', models.CharField(help_text='Insira um Emoji correspondente (ex: ☕, 🥫)', max_length=10)),
                ('preco_sats', models.IntegerField(verbose_name='Preço em Satoshis (Sats)')),
            ],
        ),
    ]
