# Generated by Django 6.0.6 on 2026-06-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Foto do Produto (Quadrada)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='icone',
            field=models.CharField(blank=True, help_text='Insira um Emoji correspondente (ex: ☕, 🥫)', max_length=10, null=True),
        ),
    ]
