# Generated by Django 6.0.6 on 2026-06-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto_imagem_alter_produto_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='is_promo',
            field=models.BooleanField(default=False, verbose_name='Exibir em Ofertas Rápidas (Máx 4)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='sku',
            field=models.CharField(blank=True, help_text='Identificador único para o JS. Ex: prod_cafe_500', max_length=50, null=True),
        ),
    ]
