# Generated by Django 6.0.6 on 2026-06-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produto_is_promo_produto_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotacaoBitcoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_brl', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ultima_atualizacao', models.DateTimeField()),
            ],
        ),
    ]
