# Generated by Django 6.0.6 on 2026-08-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_hero', models.CharField(default='Bem-vindo ao Supermercado Kix', max_length=200, verbose_name='Título do Hero')),
                ('subtitulo_hero', models.TextField(blank=True, null=True, verbose_name='Subtítulo do Hero')),
                ('imagem_hero', models.ImageField(upload_to='hero/', verbose_name='Imagem do Hero')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Configuração do Hero (Home)',
                'verbose_name_plural': 'Configurações do Hero (Home)',
            },
        ),
    ]
