# Generated by Django 6.0.6 on 2026-08-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_homeconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Macro Categoria',
                'verbose_name_plural': 'Macro Categorias',
                'ordering': ['ordem'],
            },
        ),
    ]
