# Generated by Django 6.0.6 on 2026-08-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_macrocategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_loja', models.CharField(default='Supermercado Itatingax', max_length=100)),
                ('badge_ecossistema', models.CharField(default='Membro do Ecossistema KIX', max_length=100)),
            ],
        ),
    ]
