# Generated by Django 6.0.6 on 2026-08-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='banner_texto',
            field=models.TextField(default='Logística integrada ao Ecossistema KIX. Economia real direto no caixa utilizando a eficiência da Lightning Network.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='banner_texto_economia',
            field=models.TextField(default='💡 É possível pagar utilizando o Pix estatal, mas o valor pagando direto em Satoshis é 10% menor!'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='banner_titulo',
            field=models.CharField(default='⚡ Pagamento Nativo em Satoshis', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='exibir_banner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='exibir_cotacao',
            field=models.BooleanField(default=True),
        ),
    ]
