# Generated by Django 6.0.6 on 2026-08-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_siteconfig_banner_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='meta_title',
            field=models.CharField(default='Supermercado Itatingax - Economia Real no Ecossistema', max_length=150),
        ),
    ]
