# Generated by Django 6.0.6 on 2026-08-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_siteconfig_meta_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Ex: frescos, mercearia, higiene, limpeza', unique=True)),
                ('imagem_fundo', models.ImageField(help_text='Imagem de fundo do card', upload_to='banners_cards/')),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
