# Generated by Django 6.0.6 on 2026-08-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_categoriacard'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='auth_greeting',
            field=models.CharField(default='Olá,', max_length=30),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='btn_clear_color',
            field=models.CharField(default='#ff4d4d', help_text='Cor do botão Limpar', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='btn_clear_text',
            field=models.CharField(default='🗑️ Limpar', max_length=30),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='btn_edit_color',
            field=models.CharField(default='#f7931a', help_text='Cor da borda/texto de Editar', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='btn_edit_text',
            field=models.CharField(default='Editar Endereço', max_length=30),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='btn_login_bg',
            field=models.CharField(default='#4285f4', help_text='Fundo do botão Entrar', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='btn_login_color',
            field=models.CharField(default='#ffffff', help_text='Texto do botão Entrar', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='btn_login_fallback_text',
            field=models.CharField(default='Entrar', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='btn_login_text',
            field=models.CharField(default='Entrar com o Google', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='btn_logout_bg',
            field=models.CharField(default='#dc3545', help_text='Fundo do botão Sair', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='btn_logout_color',
            field=models.CharField(default='#ffffff', help_text='Texto do botão Sair', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='btn_logout_text',
            field=models.CharField(default='Sair', max_length=30),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='btn_pay_bg',
            field=models.CharField(default='#28a745', help_text='Fundo do botão Pagar', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='btn_pay_color',
            field=models.CharField(default='#ffffff', help_text='Texto do botão Pagar', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='btn_pay_text',
            field=models.CharField(default='Pagar', max_length=30),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='header_bg_color',
            field=models.CharField(default='#1a1a1a', help_text='Cor de fundo (Hex: #1a1a1a)', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='header_text_color',
            field=models.CharField(default='#ffffff', help_text='Cor do texto principal', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='sats_color',
            field=models.CharField(default='#f7931a', help_text='Cor da palavra Sats (Hex: #f7931a)', max_length=7),
        ),
    ]
