# Generated by Django 6.0.6 on 2026-08-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_siteconfig_auth_greeting_siteconfig_btn_clear_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='badge_bg_color',
            field=models.CharField(default='#f7931a', help_text='Cor de fundo da Badge (Hex: #f7931a)', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='badge_text_color',
            field=models.CharField(default='#000000', help_text='Cor do texto da Badge (Hex: #000000)', max_length=7),
        ),
    ]
