# Generated by Django 6.0.6 on 2026-08-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_siteconfig_badge_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='banner_bg_color',
            field=models.CharField(default='#222222', help_text='Cor de fundo do banner (Hex: #222222)', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='banner_border_color',
            field=models.CharField(default='rgba(255,255,255,0.2)', help_text='Cor da linha divisória (Hex ou RGBA)', max_length=30),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='banner_cotacao_color',
            field=models.CharField(default='#ffffff', help_text='Cor do texto do preço do BTC', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='banner_economia_color',
            field=models.CharField(default='#ffb703', help_text='Cor da mensagem de economia (Hex: #ffb703)', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='banner_text_color',
            field=models.CharField(default='#dddddd', help_text='Cor do texto descritivo', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='banner_texto_cotacao',
            field=models.CharField(default='Preço atual do Bitcoin:', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='banner_title_color',
            field=models.CharField(default='#ffffff', help_text='Cor do título do banner', max_length=7),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='banner_titulo',
            field=models.CharField(default='⚡ Pagamento Nativo em Satoshis', max_length=150),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='exibir_banner',
            field=models.BooleanField(default=True, help_text='Exibir o banner promocional no topo?'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='exibir_cotacao',
            field=models.BooleanField(default=True, help_text='Exibir a cotação do Bitcoin dentro do banner?'),
        ),
    ]
