# Generated by Django 6.0.6 on 2026-08-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_siteconfig_banner_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo do Site'),
        ),
    ]
